name: daily
on:
  schedule:
    - cron: "0 1 * * *"
  repository_dispatch:
    types: [build-daily]
  workflow_dispatch:
jobs:
  build:
    if: false
    name: Build
    #runs-on: SumatraBuilder
    runs-on: windows-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v6
        with:
          # needed to calc build number via git log --oneline
          fetch-depth: 0

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - name: Build
        run: bun .\cmd\ci-daily-build.ts

      - name: Upload Windows EXE artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sumatrapdf-exe-${{ github.sha }}
          path: |
            out/rel32/*.exe
            out/rel64/*.exe
            out/arm64/*.exe
          if-no-files-found: error
